rust_dockerfile: use cmake3 (instead of 2)
snappy-sys wanted version 3. The error message is abbreviated below

error: failed to run custom build command for `snappy-sys v0.1.0 ...
process didn't exit successfully: ...
...
--- stderr
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.1 or higher is required.  You are running version 2.8.12.2